---
- name: Pull docker image of DigiCamp Frontend
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
     - name: Stop Docker container
       docker_container: 
        name: digicamp_frontend
        state: stopped

    - name: Remove Docker container
      docker_container: 
        name: digicamp_frontend
        state: absent 
        
    - name: Remove Docker image
      docker_image:
        state: absent
        name: jpray/digicamp_frontend
        tag: latest 
        
    - name: Pull devops image
      docker_image:
        name: jpray/digicamp_frontend:latest
        source: pull

    - name: deploy digicamp docker container
      docker_container:
        image: jpray/digicamp_frontend:latest
        name: digicamp
        state: started
        ports:
          - "8090:80"
... 
