---
- name: Pull docker image of DigiCamp Frontend
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Stop Docker Container
      shell: docker stop digicamp_frontend
        
    - name: Remove Docker Container
      shell: docker rm -f digicamp_frontend
        
    - name: Remove Docker Image
      shell: docker image rm -f jpray/digicamp_frontend:latest
        
    - name: Pull devops image
      docker_image:
        name: jpray/digicamp_frontend:latest
        source: pull

    - name: deploy digicamp docker container
      docker_container:
        image: jpray/digicamp_frontend:latest
        name: digicamp
        state: started
        ports:
          - "8090:80"
... 
