---
- name: Pull docker image of DigiCamp Frontend
  hosts: all
  tasks:
    - name: Stop Docker container
      docker_container: 
        name: digicamp
        state: stopped

    - name: Remove Docker container
      docker_container: 
        name: digicamp
        state: absent 
        
    - name: Remove Docker image
      docker_image:
        state: absent
        name: jpray/digicamp_frontend
        tag: latest 
        
    - name: Pull devops image
      docker_image:
        name: jpray/digicamp_frontend
        source: pull

    - name: deploy digicamp docker container
      docker_container:
        image: jpray/digicamp_frontend:latest
        name: digicamp
        state: started
        auto_remove: true
        ports:
          - "4200:80"
... 
